### ISSUE TITLE
Crash on loading unreal 4.17 & 4.18 with plugin

### ISSUE THREAD

**Issue by Jordonbc** [devdad/SimplexNoise#6]
![image](https://user-images.githubusercontent.com/16258926/36844045-f57a57e8-1d48-11e8-9cd9-d80bf11bfa3d.png)

**Comment by devdad** [comment]
Thanks for a report I will check it up.

**Comment by Jordonbc** [comment]
Here's one of the logs:
[https://gist.github.com/Jordonbc/d0e7b2dc36481242a2ac0883f6b7d892](https://gist.github.com/Jordonbc/d0e7b2dc36481242a2ac0883f6b7d892)

**Comment by devdad** [comment]
Hi I've pushed the update , and you can find binary version of the plugin in release section.

You are getting that msg because you need to build the plugin by your self or you can download binary version in release section.

[https://github.com/devdad/SimplexNoise/releases/download/SimplexNoise_UE4.18.3/SimplexNoise_UE4.18.3.zip](url)
